### ISSUE TITLE
Remove/archive v1 datasets ahead of v2 release, promote new CSVs

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/opioid-policy-scan#65]
To prepare for the upcoming release of the v2 datasets, which have been consolidated by spatial resolution and now include historical tables, we should at least move all of the old CSVs into a new directory, like `data_final/v1.1` (must double-check the actual release number here), and move the contents of `data_final/consolidated` into a more primary location. Maybe something like `data_final/v2.0/tables` and `data_final/v2.0/dictionaries`.

There is other content in the `data_final` directory that we'll have to figure out what to do with, but this ticket only concerns the old and new CSVs.

**Comment by bucketteOfIvy** [comment]
Working on this now!

With regards to version numbers: looking at Zenodo, v1.0 appears to have been the only official "release." However, `data_final` currently includes historic data not present in the `v1.0` release, so it feels fair to refer to the current contents of `data_final` as `v1.1` (since it contains strictly more data than `v1.0`), so I'm running with `v1.1` as the file name.

**Comment by mradamcox** [comment]
Gotchya. The Zenodo releases are based on this repo's [releases](https://github.com/GeoDaCenter/opioid-policy-scan/releases), I see now it was 1.0-alpha and 1.0. I'd say v1.1 is ok for now, as you have.
